dsx_files = "This option specifies the files to use for the extraction of the dsx values."
xscore_files = "This option specifies the files to use for the extraction of the xscore values."
binana_files = "This option specifies the files to use for the extraction of the binana values."
mmgbsa_files = "This option specifies the files to use for the extraction of the mmgbsa values."
rf_score_file = "This option specifies the files to use for the extraction of the rf_score values."
vina_files = "This option specifies the files to use for the extraction of the vina values."
xglide_file = "This option specifies the log file from xglide to use for the extraction of glide values."
energies_file = "This option specifies the file containing the experimental energies for all the systems."
convert = "This option establishes the scoring functions to convert to energy value from pkd. "
conversion_temperature = "The temperature value to use when converting from pkd to energy."
conversion_r_value = "The r value to use when converting from pkd to energy."
output_general_name = "The complete path to where the output should be written plus the prefix for the files."
rotable_bonds_files = "The .pdbqt files to analyze and extract the rotable bonds from."
log_file = "A complte filename for the log file."
mmgbsa_as_sf = "If this option is present the program will extract the total value of prime-mmgbsa as a " \
               "scoring function, otherwise it will extract only the descriptors."
pele_file = "The pele containing the scores to use"
glide_ranking_csv_file = "This option expects two terms. One is a .csv file generated by exporting the " \
                         "spreadsheet from Maestro, it should contain the fields Title and docking score at least, " \
                         "and it should have the same order" \
                         "as the order used when extracting the compounds to launch the simulations. " \
                         "The other term is going to be used as the prefix for the simulations id, so it should " \
                         "correspond with the prefix used as base name when exporting the structures from Maestro."
