pele_folders = "/home/kqtw353/stay/external_software/PELErev12349"
schrodinger_path = "/opt/az/schrodinger/schrodinger_suite/2016.03"
plop_path = "/home/kqtw353/stay/work/PlopRotTemp/PlopRotTemp.py"
conformational_template = "/home/kqtw353/stay/work/conformational_search_pele_template.conf"
pele_license_path = "/home/kqtw353/stay/external_software/PELErev12279"
default_every = 1
constraints_strength = 0.2
receptor_file_default = ""
log_file_default = "log.txt"
subfolders_path_default = "./"
adaptive_sampling_def = ""
adaptive_sampling_keywords = ['COMPLEXES', 'SEED', 'OUTPUT_PATH', "PELE_STEPS"]
atoms2apply_constraints_default = [" CA "]
mutations_program_path = "/home/kqtw353/stay/work/mutations_program/mutations_program.py"
obc_param_generator_path = "/home/kqtw353/stay/work/OBCparamsgen/solventOBCParamsGenerator.py"
ligand_chain = "Z"
