pele_folders = "/home_old/jelisa"
schrodinger_path = '/home/jelisa/programs/Schrodinger_Suites_2017-1_Advanced_Linux-x86_64'
plop_path = "/home_old/jelisa/PhD_work/plopRotTemp/ploProtTemp_repos/PlopRotTemp.py"
conformational_template = "/home_old/kqtw353/stay/work/conformational_search_pele_template.conf"
pele_license_path = "/gpfs/projects/bsc72/PELE++/license"
default_every = 10
constraints_strength = 0.2
receptor_file_default = ""
log_file_default = "sims_prep_log.txt"
subfolders_path_default = "./"
adaptive_sampling_def = ""
adaptive_sampling_keywords = ['COMPLEXES', 'SEED', 'OUTPUT_PATH', "PELE_STEPS"]
atoms2apply_constraints_default = [" CA "]
mutations_program_path = "/home_old/jelisa/PhD_work/vs_scripts/mutations_program/mutations_program.py"
obc_param_generator_path = "/home_old/jelisa/PhD_work/binding_affinity/Scripts/solventOBCParamsGenerator.py"
ligand_chain = "Z"
conf_file_suffix = ""
