all_sfs_file_help = "The file containing all the S.F. to analyze, except the initial glide and the PELE energies, " \
                    "which are read from another file."
pele_best_energy_file_help = "The file containing the best PELE energy, or any PELE energy, the file should have" \
                             "the format of the minimum_PELE_binding_energies.csv file generated " \
                             "by structure_selection.py"
pele_initial_struct_filename_help = "The file containing the PELE energy for the initial structure, or any PELE" \
                                    " energy, the file should have the format of the " \
                                    "minimum_PELE_binding_energies.csv file generated by structure_selection.py"
initial_glide_filename_help = "The .csv exported from glide containing the initial value of glide"
general_title_help = "The common part for the titles of the images generated."
output_prefix_help = "The common prefix to be used when naming all the files generated."
activities_file_help = "The file containing the mapping between the molecule identifier, the simulation identifier and " \
                       "the activity values."
