program_description = "A program to compute the number of actives, inactives (or decoys) and the percentage of " \
                      "active compounds in a given dataset. It coniders 4 steps on the VS procedue: initial," \
                      " after glide, into pele and after pele. For the initial step it reads the information " \
                      "from the actives and inactives files in any if the formats accepted by openbabel. This" \
                      "step represents how many compounds/variants are in the DUD-e dataset for the receptor." \
                      "For the after glide step it reads the information from the glide_ranking file. This step" \
                      "represents how many of the compounds/variants have been docked into the receptor by glide." \
                      "And for the into pele and after pele steps it reads the information from the simulation_report" \
                      "file. The into pele step represents how many compound/variants have been selected and " \
                      "used to run a PELE simulation, in this step we stop counting those compounds/variants " \
                      "selected but with problems during the templates generation. The after pele represent " \
                      "how many of the compounds/variants have successfully finished the PELE simulations."
output_default_name = "dataset_composition_summary.csv"
actives_file_help = "The file containing all the active molecules. " \
                    "It's able to read the formats allowed by pybel: .pdb, .mol2, .sdf, etc."
inactives_file_help = "The file containing all the inactive molecules. " \
                      "It's able to read the formats allowed by pybel: .pdb, .mol2, .sdf, etc."
glide_ranking_help = "A .csv file containing the ranking from glide. It should be the file" \
                     "extracted when the first docking is done, and the compounds should be correctly ordered."
simulations_report_help = "The file generated by sims_review.py script containing the simulations report."
output_file_help = "The name of the output file to be generated."
