pele_folders = "/home/kqtw353/stays/external_software/PELErev12349"
schrodinger_path = "/opt/az/schrodinger/schrodinger_suite/2016.03"
plop_path = "/home/kqtw353/stays/group_software/PlopRotTemp/PlopRotTemp.py"
conformational_template = "/projects/kqtw353-Jelisa-Iglesias/may_stay/conformational_search_pele_template.conf"
pele_license_path = "/home/kqtw353/stays/external_software/PELErev12279"
default_every = 1
constraints_strength = 0.2
atoms2apply_constraints_default = [" CA "]
mutations_program_path = "/home/kqtw353/stays/september_stay/work/mutations_program/mutations_program.py"
obc_param_generator_path = "/home/kqtw353/stays/group_software/OBCparamsgen/solventOBCParamsGenerator.py"
ligand_chain = "Z"
